# ExportUnitBlueprintValues.py
# Run inside Unreal Editor (Python console or: Tools -> Execute Python Script).
# Writes Docs/Units-BlueprintValues.md with CDO property values for reference units.

import json
import unreal
from pathlib import Path

PROJECT_ROOT = Path(unreal.Paths.project_dir())
OUTPUT_MD = PROJECT_ROOT / "Docs" / "Units-BlueprintValues.md"
OUTPUT_JSON = PROJECT_ROOT / "Docs" / "Units-BlueprintValues.json"

UNIT_ASSETS = [
    "/Game/Blueprint/Units/Shooter/BP_Shooter",
    "/Game/Blueprint/Units/Lancer/BP_Lancer",
    "/Game/Blueprint/Units/Hunter/BP_Hunter",
]

PROJECTILE_ASSETS = [
    "/Game/Blueprint/Units/Shooter/BP_ShooterProjectile",
    "/Game/Blueprint/Units/Lancer/BP_PlasmaShotProjectile",
    "/Game/Blueprint/Units/Hunter/BP_HunterGunProjectile",
    "/Game/Blueprint/Units/Hunter/BP_RocketProjectile",
]

COMPONENT_FILTER = (
    "UnitLogic",
    "UnitParameters",
    "UnitShieldParameters",
    "UniversalWeaponController",
    "UnitMovement",
    "UnitScrapDestroy",
    "UnitBasicDestroy",
    "HunterAnimation",
    "LancerCannonAnimation",
    "HealthBar",
    "Box",
    "Ground",
)

PROPERTY_PREFIXES = ("m_",)
PROPERTY_WHITELIST = {
    "AIControllerClass",
    "MaxSpeed",
    "Projectile prefab",
    "Scrap prefab",
    "Explosion particle prefab",
}


def _serialize(value):
    if value is None:
        return None
    if isinstance(value, (bool, int, float, str)):
        return value
    if isinstance(value, (list, tuple)):
        return [_serialize(v) for v in value]
    if isinstance(value, dict):
        return {str(k): _serialize(v) for k, v in value.items()}
    type_name = type(value).__name__
    if type_name in ("SoftClassProperty", "SoftObjectProperty"):
        try:
            return str(value)
        except Exception:
            return type_name
    if hasattr(value, "get_name"):
        try:
            return value.get_name()
        except Exception:
            pass
    if hasattr(value, "get_path_name"):
        try:
            return value.get_path_name()
        except Exception:
            pass
    return str(value)


def _should_export(prop_name: str) -> bool:
    if prop_name in PROPERTY_WHITELIST:
        return True
    return any(prop_name.startswith(prefix) for prefix in PROPERTY_PREFIXES)


def _dump_object(obj, title: str) -> dict:
    result = {"_title": title, "_class": obj.get_class().get_name()}
    for prop in obj.get_class().properties():
        name = prop.get_name()
        if not _should_export(name):
            continue
        try:
            result[name] = _serialize(obj.get_editor_property(name))
        except Exception:
            continue
    return result


def _dump_actor_cdo(asset_path: str) -> dict:
    asset = unreal.load_asset(asset_path)
    if asset is None:
        return {"asset": asset_path, "error": "asset not found"}

    gen_class = asset.generated_class()
    cdo = unreal.get_default_object(gen_class)

    entry = {
        "asset": asset_path,
        "generated_class": gen_class.get_name(),
        "parent_class": gen_class.get_super_class().get_name(),
        "actor": _dump_object(cdo, gen_class.get_name()),
        "components": [],
    }

    try:
        entry["actor"]["AIControllerClass"] = _serialize(cdo.get_editor_property("AIControllerClass"))
    except Exception:
        pass

    for comp in cdo.get_components_by_class(unreal.ActorComponent):
        comp_name = comp.get_name()
        comp_class = comp.get_class().get_name()
        if not any(token in comp_name or token in comp_class for token in COMPONENT_FILTER):
            continue
        dumped = _dump_object(comp, comp_name)
        dumped["_component_class"] = comp_class
        entry["components"].append(dumped)

    return entry


def _to_markdown(data: dict) -> str:
    lines = [
        "# Blueprint Unit Parameter Values",
        "",
        "> Auto-generated by `Scripts/ExportUnitBlueprintValues.py`.",
        "> Refresh: Unreal Editor → Execute Python Script → this file.",
        "> Curated unit docs: [CurrentUnits.md](./CurrentUnits.md).",
        "",
    ]

    for section_key, section_title in (("units", "Units"), ("projectiles", "Projectiles")):
        lines.append(f"## {section_title}")
        lines.append("")
        for item in data.get(section_key, []):
            if "error" in item:
                lines.append(f"### {item['asset']}")
                lines.append(f"- **Error:** {item['error']}")
                lines.append("")
                continue

            lines.append(f"### `{item['asset']}`")
            lines.append(f"- **Class:** `{item['generated_class']}`")
            lines.append(f"- **Parent:** `{item['parent_class']}`")
            lines.append("")

            actor = item.get("actor", {})
            lines.append("#### Actor (CDO)")
            lines.append("")
            lines.append("| Parameter | Value |")
            lines.append("|----------|----------|")
            for key, val in sorted(actor.items()):
                if key.startswith("_"):
                    continue
                lines.append(f"| `{key}` | `{val}` |")
            lines.append("")

            for comp in item.get("components", []):
                lines.append(f"#### {comp.get('_title')} (`{comp.get('_component_class')}`)")
                lines.append("")
                lines.append("| Parameter | Value |")
                lines.append("|----------|----------|")
                for key, val in sorted(comp.items()):
                    if key.startswith("_"):
                        continue
                    lines.append(f"| `{key}` | `{val}` |")
                lines.append("")

    return "\n".join(lines)


def main():
    data = {
        "units": [_dump_actor_cdo(path) for path in UNIT_ASSETS],
        "projectiles": [_dump_actor_cdo(path) for path in PROJECTILE_ASSETS],
    }

    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_MD.parent.mkdir(parents=True, exist_ok=True)

    OUTPUT_JSON.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    OUTPUT_MD.write_text(_to_markdown(data), encoding="utf-8")

    unreal.log(f"Exported blueprint values to {OUTPUT_MD}")
    print(f"OK: {OUTPUT_MD}")


if __name__ == "__main__":
    main()
else:
    main()
